- name: DB setup
  hosts: db
  tasks:
  
  - name: Installing mysql-server
    ansible.builtin.command: sudo dnf install mysql-server -y
      register: mysqlserver
  
  -name: Checking the server install msg
   ansible.builtin.debug:
    msg: {{mysqlserver}}
  
    