- name: DB setup
  hosts: db
  become: yes
  vars:
    login_host: 172.31.57.111
  vars_prompt:
  - name: mysql_password
    prompt: Please Enter Password-
    private: no
  tasks:
  
  - name: Installing mysql-server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  
  - name: Enabling and starting mysql
    ansible.builtin.service:
      state: started
      enabled: yes
  
  - name: Install python mysql dependencies
    ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography
      executable: pip 3.9
      
  

  
  
    